### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by aloasut** [laravel-admin-extensions/wangEditor#1]
laradock@d757dc4c3490:/var/www$ composer require laravel-admin-ext/wang-editor
Using version ^0.0.1 for laravel-admin-ext/wang-editor
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In WangEditorServiceProvider.php line 16:
                                                                 
  Call to undefined method Encore\WangEditor\WangEditor::boot()  
                                                                 

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by z-song** [comment]
Wha't the laravel-admin version do you installed?

**Comment by aloasut** [comment]
PHP version | PHP/7.2.4
Laravel version | 5.5.43
Laravel-admin version   1.5.x-dev

Thanks

**Comment by z-song** [comment]
Update laravel-admin then try again

**Comment by aloasut** [comment]
Sorry  got the same problem after upgrading to the latest version

###   **- Updating encore/laravel-admin (1.5.x-dev f2450dd => v1.5.19):  Checking out 9841d34ca0**

laradock@d757dc4c3490:/var/www$ composer require laravel-admin-ext/wang-editor
Using version ^0.0.1 for laravel-admin-ext/wang-editor
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing laravel-admin-ext/wang-editor (0.0.1): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In WangEditorServiceProvider.php line 16:
                                                                 
  Call to undefined method Encore\WangEditor\WangEditor::boot()  
                                                                 

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by z-song** [comment]
```bash
composer require laravel-admin 1.5.x-dev
```

**Comment by z-song** [comment]
@aloasut update to version `dev-master`
```bash
composer require encore/laravel-admin dev-master
```
