### ISSUE TITLE
Error Field type [editor] does not exist.已解决

### ISSUE THREAD

**Issue by phpervip** [laravel-admin-extensions/wangEditor#14]
如果用的是laravel-admin, versions : * v1.7.5
按说明配置完，会报上面的错
Error Field type [editor] does not exist.
应修改app/Admin/bootstrap.php
为
Encore\Admin\Form::forget(['map']);
即去掉：editor

**Comment by jonexyz** [comment]
按上所述，问题已解决

**Comment by ygcool** [comment]
谢谢，按照此方法，问题已解决

**Comment by wukong010** [comment]
version: ^1.7 按上所述，问题已解决
