### ISSUE TITLE
Field type [editor] does not exist.

### ISSUE THREAD

**Issue by jdi6668** [laravel-admin-extensions/wangEditor#15]
没有解决，按照首页文档操作
版本
php 7.2.23
laravel 5.5.*
wang-editor ^1.1
laravel-admin 1.7.7

**Comment by sunxiyuan** [comment]
我也遇到同样的问题

**Comment by sunxiyuan** [comment]
在app/Admin/bootstrap.php中加入以下内容即可。
Encore\Admin\Form::extend('editor', Encore\WangEditor\Editor::class);

**Comment by z-song** [comment]
参考 #14
