### ISSUE TITLE
require 报错 laravel-admin 1.7.8

### ISSUE THREAD

**Issue by haopengfly** [laravel-admin-extensions/wangEditor#16]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: encore/laravel-admin[v1.7.8, dev-master].
    - Can only install one of: encore/laravel-admin[v1.7.8, dev-master].
    - Can only install one of: encore/laravel-admin[v1.7.8, dev-master].
    - Installation request for encore/laravel-admin 1.7.8 -> satisfiable by encore/laravel-admin[v1.7.8].
    - Installation request for encore/laravel-admin (locked at dev-master, required as 1.7.8) -> satisfiable by encore/laravel-admin[dev-master].

**Comment by z-song** [comment]
已修复
