### ISSUE TITLE
error in install

### ISSUE THREAD

**Issue by nightw0lv** [laravel-admin-extensions/wangEditor#2]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/framework v5.7.2 conflicts with laravel/framework[5.5.x-dev].
    - laravel/framework 5.5.x-dev conflicts with laravel/framework[v5.7.2].
    - laravel/framework 5.5.x-dev conflicts with laravel/framework[v5.7.2].
    - laravel-admin-ext/wang-editor 0.0.1 requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].
    - Installation request for laravel-admin-ext/wang-editor ^0.0.1 -> satisfiable by laravel-admin-ext/wang-editor[0.0.1].
    - Installation request for laravel/framework (locked at v5.7.2, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.2].

Installation failed, reverting ./composer.json to its original content.

**Comment by z-song** [comment]
如果还有这个问题，请重新打开
