### ISSUE TITLE
image upload only can use base64?

### ISSUE THREAD

**Issue by youruan** [laravel-admin-extensions/wangEditor#9]
now image upload only can use base64? and i set the config `uploadImgServer` is not effective

**Comment by pandoraes** [comment]
我也有这个问题

**Comment by cnny** [comment]
me too

**Comment by AvatarBB** [comment]
我也有这个问题 怎么解决啊

**Comment by phpervip** [comment]
怎么能配置上传到服务器呢？我在网上找了两篇文章，都会报错。zong，你能写一篇文档吗？非常谢谢!

**Comment by z-song** [comment]
都不贴报错信息，我怎么知道问题在哪里。。。

**Comment by z-song** [comment]
@youruan @pandoraes @AvatarBB @phpervip https://github.com/laravel-admin-extensions/wangEditor/blob/master/README.md#%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87
